#ifndef FERRITE_INPUT_H
#define FERRITE_INPUT_H

#include <stdint.h>

typedef enum FERRITE_KEY_CODE {
	FERRITE_KEY_UNKNOWN = -1,
	FERRITE_KEY_ESCAPE = 0,
	FERRITE_KEY_F1,
	FERRITE_KEY_F2,
	FERRITE_KEY_F3,
	FERRITE_KEY_F4,
	FERRITE_KEY_F5,
	FERRITE_KEY_F6,
	FERRITE_KEY_F7,
	FERRITE_KEY_F8,
	FERRITE_KEY_F9,
	FERRITE_KEY_F10,
	FERRITE_KEY_F11,
	FERRITE_KEY_F12,
	FERRITE_KEY_TILDE,
	FERRITE_KEY_1,
	FERRITE_KEY_2,
	FERRITE_KEY_3,
	FERRITE_KEY_4,
	FERRITE_KEY_5,
	FERRITE_KEY_6,
	FERRITE_KEY_7,
	FERRITE_KEY_8,
	FERRITE_KEY_9,
	FERRITE_KEY_0,
	FERRITE_KEY_MINUS,
	FERRITE_KEY_EQUALS,
	FERRITE_KEY_BACKSPACE,
	FERRITE_KEY_TAB,
	FERRITE_KEY_A,
	FERRITE_KEY_B,
	FERRITE_KEY_C,
	FERRITE_KEY_D,
	FERRITE_KEY_E,
	FERRITE_KEY_F,
	FERRITE_KEY_G,
	FERRITE_KEY_H,
	FERRITE_KEY_I,
	FERRITE_KEY_J,
	FERRITE_KEY_K,
	FERRITE_KEY_L,
	FERRITE_KEY_M,
	FERRITE_KEY_N,
	FERRITE_KEY_O,
	FERRITE_KEY_P,
	FERRITE_KEY_Q,
	FERRITE_KEY_R,
	FERRITE_KEY_S,
	FERRITE_KEY_T,
	FERRITE_KEY_U,
	FERRITE_KEY_V,
	FERRITE_KEY_W,
	FERRITE_KEY_X,
	FERRITE_KEY_Y,
	FERRITE_KEY_Z,
	FERRITE_KEY_LBRACKET,
	FERRITE_KEY_RBRACKET,
	FERRITE_KEY_BACKSLASH,
	FERRITE_KEY_SEMICOLON,
	FERRITE_KEY_APOSTROPHE,
	FERRITE_KEY_COMMA,
	FERRITE_KEY_PERIOD,
	FERRITE_KEY_SLASH,
	FERRITE_KEY_SPACE,
	FERRITE_KEY_ENTER,
	FERRITE_KEY_INSERT,
	FERRITE_KEY_DELETE,
	FERRITE_KEY_HOME,
	FERRITE_KEY_END,
	FERRITE_KEY_PAGEUP,
	FERRITE_KEY_PAGEDOWN,
	FERRITE_KEY_UP,
	FERRITE_KEY_DOWN,
	FERRITE_KEY_LEFT,
	FERRITE_KEY_RIGHT,
	FERRITE_KEY_KP_DIVIDE,
	FERRITE_KEY_KP_MULTIPLY,
	FERRITE_KEY_KP_MINUS,
	FERRITE_KEY_KP_PLUS,
	FERRITE_KEY_KP_ENTER,
	FERRITE_KEY_KP_1,
	FERRITE_KEY_KP_2,
	FERRITE_KEY_KP_3,
	FERRITE_KEY_KP_4,
	FERRITE_KEY_KP_5,
	FERRITE_KEY_KP_6,
	FERRITE_KEY_KP_7,
	FERRITE_KEY_KP_8,
	FERRITE_KEY_KP_9,
	FERRITE_KEY_KP_0,
	FERRITE_KEY_KP_PERIOD,
} FERRITE_KEY_CODE;

typedef enum FERRITE_KEY_MOD {
	FERRITE_KEY_MOD_SHIFT = 0x0001,
	FERRITE_KEY_MOD_CTRL = 0x0002,
	FERRITE_KEY_MOD_ALT = 0x0004,
	FERRITE_KEY_MOD_SUPER = 0x0008,
} FERRITE_KEY_MOD;

typedef enum FERRITE_KEY_ACTION {
	FERRITE_KEY_ACTION_PRESS,
	FERRITE_KEY_ACTION_RELEASE,
	FERRITE_KEY_ACTION_HOLD,
} FERRITE_KEY_ACTION;

typedef enum FERRITE_MOUSE_BUTTON {
	FERRITE_MOUSE_BUTTON_LEFT,
	FERRITE_MOUSE_BUTTON_RIGHT,
	FERRITE_MOUSE_BUTTON_MIDDLE,
	FERRITE_MOUSE_BUTTON_4,
	FERRITE_MOUSE_BUTTON_5,
	FERRITE_MOUSE_BUTTON_6,
	FERRITE_MOUSE_BUTTON_7,
	FERRITE_MOUSE_BUTTON_8,
} FERRITE_MOUSE_BUTTON;

typedef enum FERRITE_MOUSE_ACTION {
	FERRITE_MOUSE_ACTION_PRESS,
	FERRITE_MOUSE_ACTION_RELEASE,
	FERRITE_MOUSE_ACTION_HOLD,
	FERRITE_MOUSE_ACTION_SCROLL,
	FERRITE_MOUSE_ACTION_MOVE,
	FERRITE_MOUSE_ACTION_ENTER,
	FERRITE_MOUSE_ACTION_LEAVE,
} FERRITE_MOUSE_ACTION;

typedef enum FERRITE_GAMEPAD_BUTTONS {
	FERRITE_GAMEPAD_BUTTON_A,
	FERRITE_GAMEPAD_BUTTON_B,
	FERRITE_GAMEPAD_BUTTON_X,
	FERRITE_GAMEPAD_BUTTON_Y,
	FERRITE_GAMEPAD_BUTTON_LB,
	FERRITE_GAMEPAD_BUTTON_RB,
	FERRITE_GAMEPAD_BUTTON_BACK,
	FERRITE_GAMEPAD_BUTTON_START,
	FERRITE_GAMEPAD_BUTTON_LT,
	FERRITE_GAMEPAD_BUTTON_RT,
	FERRITE_GAMEPAD_BUTTON_DUP,
	FERRITE_GAMEPAD_BUTTON_DDOWN,
	FERRITE_GAMEPAD_BUTTON_DLEFT,
	FERRITE_GAMEPAD_BUTTON_DRIGHT,
	FERRITE_GAMEPAD_BUTTON_LSTICK,
	FERRITE_GAMEPAD_BUTTON_RSTICK,
} FERRITE_GAMEPAD_BUTTONS;

typedef enum FERRITE_GAMEPAD_STICKS {
	FERRITE_GAMEPAD_STICK_LEFT,
	FERRITE_GAMEPAD_STICK_RIGHT,
} FERRITE_GAMEPAD_STICKS;

typedef enum FERRITE_GAMEPAD_ACTION {
	FERRITE_GAMEPAD_ACTION_PRESS,
	FERRITE_GAMEPAD_ACTION_RELEASE,
	FERRITE_GAMEPAD_ACTION_HOLD,
	FERRITE_GAMEPAD_ACTION_POS_X,
	FERRITE_GAMEPAD_ACTION_POS_Y,
} FERRITE_GAMEPAD_ACTION;

typedef enum ferrite_input_device_t {
	FERRITE_INPUT_DEVICE_KEYBOARD,
	FERRITE_INPUT_DEVICE_MOUSE,
	FERRITE_INPUT_DEVICE_JOYSTICK,
	FERRITE_INPUT_DEVICE_TOUCH,
	FERRITE_INPUT_DEVICE_GAMEPAD,
	FERRITE_INPUT_DEVICE_UNKNOWN
} ferrite_input_device_t;

typedef struct ferrite_kbd_event_t {
	FERRITE_KEY_CODE key;
	FERRITE_KEY_MOD mod;
	FERRITE_KEY_ACTION action;
} ferrite_kbd_event_t;

typedef struct ferrite_mouse_event_t {
	int32_t x;
	int32_t y;
	FERRITE_MOUSE_BUTTON button;
	FERRITE_MOUSE_ACTION action;
} ferrite_mouse_event_t;

typedef struct ferrite_gamepad_event_t {
	FERRITE_GAMEPAD_BUTTONS button;
	FERRITE_GAMEPAD_STICKS stick;
	FERRITE_GAMEPAD_ACTION action;
	float value;
} ferrite_gamepad_event_t;

typedef struct ferrite_win_event_t {
	ferrite_input_device_t device;
	union {
		ferrite_kbd_event_t kbd;
		ferrite_mouse_event_t mouse;
		ferrite_gamepad_event_t gamepad;
	};
} ferrite_win_event_t;

#endif // FERRITE_INPUT_H
